databases:
  - name: mynewproject_db
    plan: free
    databaseName: mynewproject
    user: mynewproject

services:
  - type: web
    plan: free
    name: mynewproject
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "pipenv run daphne -b 0.0.0.0 mynewproject.asgi:application"
    envVars:
      - key: USE_POSTGRES
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: mynewproject_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4