databases:
  - name: mynewproject_db
    plan: basic-1gb
    region: ohio
    databaseName: mynewproject
    user: mynewproject

services:
  - type: web
    plan: starter
    name: mynewproject
    runtime: python
    region: ohio
    buildCommand: "./build.sh"
    startCommand: "pipenv run daphne -b 0.0.0.0 mynewproject.asgi:application"
    envVars:
      - key: USE_POSTGRES
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: mynewproject_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: CELERY_BROKER_URL
        fromService:
          name: mynewproject-celery-redis
          type: redis
          property: connectionString
  - type: worker
    name: mynewproject-celery-worker
    env: python
    region: ohio
    buildCommand: "./build.sh"
    startCommand: "celery --app=mynewproject worker --loglevel info --concurrency 4"
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: mynewproject-celery-redis
          type: redis
          property: connectionString
      - key: USE_POSTGRES
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: mynewproject_db
          property: connectionString
  - type: redis
    name: mynewproject-celery-redis
    region: ohio
    plan: starter 
    maxmemoryPolicy: noeviction 
    ipAllowList: []
  